### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by PoonamZ** [Kalit31/Land-Cover-Analysis#1]
Please can you provide the dataset used.

**Comment by Kalit31** [comment]
Hi,
I had used Google Earth Engine to get the datasets and later on extracted the required bands using gdal. 
You may obtain the required region of images from GEE. 

The dataset I used is quite large and is messed up currently. Yet, I am attaching it here.
https://drive.google.com/drive/folders/1ZMlwmboKkTi8bayKyeEBa1XTiHCbLtBa?usp=sharing

**Comment by PoonamZ** [comment]
Thanks.
