### ISSUE TITLE
Image Processing 

### ISSUE THREAD

**Issue by zafor44** [Kalit31/Land-Cover-Analysis#15]
Sir 
I want to know the image processing technique using Gdal that you have used in this paper.
also please make a serial of the code that have used in your project work.
I did understood the image processing step that you have been discussed.

**Comment by Kalit31** [comment]
Hi @zafor44,
Sorry for the late response, just saw your message.
You can find the gdal specific code here: https://github.com/Kalit31/Land-Cover-Analysis/blob/master/Sentinel-2-MSI-1C:4-bands/convertTo4Bands. The 'gdal_translate' is used to extract the required bands, and gdal_merge is used to merge the extracted bands into one single image according to the specified order of bands. Other than that gdal was just used to read 'tiff' images. You can find it here: https://github.com/Kalit31/Land-Cover-Analysis/blob/master/Sentinel-2-MSI-1C:4-bands/image_processing_functions.py

**Comment by zafor44** [comment]
Sir
After the download of satellite data what types of steps should I follow to prepare the training and testing sample for CNN.
WOULD YOU PLEASE MAKE A SHORT VIDEO REGARDING THIS ISSUE.
I AM VERY MUCH GRATE FULL TO YOU IF YOU SHOW THE PROCESS BY MAKE A SHORT VIDEO OR MAKE A ZOOM CONVERSATION WITH ME.
THANKS AND REGARDS
