### ISSUE TITLE
To extract out B2, B3, B4, B8 bands and merge them 

### ISSUE THREAD

**Issue by zafor44** [Kalit31/Land-Cover-Analysis#18]
from where did you get it or how could I use it
![RGB lulc](https://user-images.githubusercontent.com/95949556/166509893-d9e6c1bb-e088-4e8a-9613-d24eb7c82693.JPG)

**Comment by Kalit31** [comment]
Hi @zafor44,
Do you mean the images? I downloaded them from Google Earth Engine. You could mail me at inanikalit31@gmail.com for further discussion, instead of opening issues here.
